basic_settings:
  site_title: Jasmine Hao
  site_emailto:  ''
  site_tagline: Ph.D candidate, Vancouver School of Economics
  favicon_image: /images/favicon.png

# markdown: kramdown
markdown: maruku

header_settings:
  avatar_image: 
  logo_image: 
  logo_width: 20

menu_settings:
  menu_items:
    - title: 'ABOUT'
      url: '/'
    - title: 'RESEARCH'
      url: '/research'
    - title: 'TEACHING'
      url: '/teaching'
    - title: 'C.V.'
      url: '/cv'
    - title: 'BLOG'
      url: '/projects'
    

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/haojasmine@gmail.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/jasmine.hao'
  twitter_url: 'https://twitter.com/JasmineHao2'
  instagram_url: 'https://www.instagram.com/jasminefish000/'
  github_url: 'https://github.com/JasmineHao'
  reddit_url: 'https://www.reddit.com/user/jasminefish000'
  linkedin_url: 'https://www.linkedin.com/in/jasminehao/'

color_settings:
  # background_color: '#ffffff'
  # background_alt_color: '#f4f5f6'
  # text_dark_color: '#2A2F36'
  # text_medium_color: '#6C7A89'
  # text_light_color: '#ABB7B7'
  # accent_color: '#ee983d'
  # border_color: '#f7d7b6'
  # overlay_background_color: '#161B21'
  # overlay_text_color: '#ffffff'
  # error_color: '#D64541'

  # background_color: '#EDDCD2'
  # background_alt_color: '#CB997E'
  # text_dark_color: '#373737'
  # text_medium_color: '#5B5B5B'
  # text_light_color: '#878787'
  # accent_color: '#A5A58D'
  # border_color: '#B7B7A4'
  # overlay_background_color: '#161B21'
  # overlay_text_color: '#DCD0C0'
  # error_color: '#D64541'

  background_color: '#EDDCD2'
  background_alt_color: '#EDC787'
  text_dark_color: '#373737'
  text_medium_color: '#5B5B5B'
  text_light_color: '#123C69'
  accent_color: '#BAB285'
  border_color: '#BAB285'
  overlay_background_color: '#161B21'
  overlay_text_color: '#DCD0C0'
  error_color: '#D64541'


font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  # title_font: '"Nunito", sans-serif'
  # body_font: '"Nunito", sans-serif'
  title_font: '"Georgia", serif'
  body_font: '"Georgia", serif'
  
  # title_font: '"Arial", serif'
  # body_font: '"Arial", serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 18
    medium_size: 19
    large_size: 20
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 12
    medium_size: 13
    large_size: 14
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 11
    medium_size: 13
    large_size: 15
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 600
    letter_spacing: 0
    line_height: 1.5
  h3:
    small_size: 14
    medium_size: 15
    large_size: 16
    weight: 200
    letter_spacing: 0
    line_height: 1.5
  h4:
    small_size: 14
    medium_size: 15
    large_size: 16
    weight: 200
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 12
    medium_size: 13
    large_size: 14
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 12
    medium_size: 13
    large_size: 14
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 12
    medium_size: 13
    large_size: 14
    weight: 200
    letter_spacing: 0
    line_height: 1.6
  
  blockquote:
    small_size: 20
    medium_size: 30
    large_size: 40
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
