basic_settings:
  site_title: Jasmine Hao
  site_tagline: Ph.D candidate, Vancouver School of Economics
  favicon_image: /images/favicon.png

# markdown: kramdown
markdown: maruku

header_settings:
  avatar_image: /images/headshot_casual.png
  logo_image:
  logo_width: 400

menu_settings:
  menu_items:
    - title: 'Working Projects'
      url: '/'
    - title: 'Other Projects'
      url: '/projects'
    - title: 'About'
      url: '/about'
    - title: 'Thanks'
      url: '/thanks'
    # - title: 'Contact'
    #   url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/haojasmine@gmail.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/jasmine.hao'
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/jasminefish000/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: 'https://www.pinterest.ca/haojasmine/'
  medium_url: 'https://medium.com/@jasminehao'
  quora_url: 'https://www.quora.com/profile/Jasmine-Hao'
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/JasmineHao'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/jasminehao/'

color_settings:
  # background_color: '#ffffff'
  # background_alt_color: '#f4f5f6'
  # text_dark_color: '#2A2F36'
  # text_medium_color: '#6C7A89'
  # text_light_color: '#ABB7B7'
  # accent_color: '#ee983d'
  # border_color: '#f7d7b6'
  # overlay_background_color: '#161B21'
  # overlay_text_color: '#ffffff'
  # error_color: '#D64541'

  background_color: '#F4F4F4'
  background_alt_color: '#C0B283'
  text_dark_color: '#373737'
  text_medium_color: '#5B5B5B'
  text_light_color: '#878787'
  accent_color: '#C0B283'
  border_color: '#f7d7b6'
  overlay_background_color: '#161B21'
  overlay_text_color: '#DCD0C0'
  error_color: '#D64541'


font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  # title_font: '"Nunito", sans-serif'
  # body_font: '"Nunito", sans-serif'
  title_font: '"Arial", serif'
  body_font: '"Arial", serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 22
    medium_size: 27
    large_size: 35
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 11
    medium_size: 13
    large_size: 15
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 11
    medium_size: 13
    large_size: 15
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 22
    medium_size: 33
    large_size: 45
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 17
    medium_size: 33
    large_size: 45
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 17
    medium_size: 20
    large_size: 25
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 12
    medium_size: 17
    large_size: 17
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 12
    medium_size: 15
    large_size: 15
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 12
    medium_size: 15
    large_size: 15
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 12
    medium_size: 14
    large_size: 17
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 20
    medium_size: 30
    large_size: 40
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
